PLEX:
  PLEX_ACCESS_TOKEN: _U9eLYsMyzwaaJpgzCfT
  PMS_PORT: '32400'
  PMS_PROTOCOL: http
  PMS_URL: 192.168.1.133
PLEX_LOGIN:
  PLEX_API_URL: https://plex.tv/api/v2
  PLEX_LOGIN_TIMEOUT: 120
PLEX_SERIES_SHUFFLER:
  PORT: 5000
  PRODUCT_NAME: Series Shuffler
